In [9]:
import pandas as pd

inventory = pd.read_csv('../data/raw/inventory_master.csv')
inventory.head()

,product_id,branch_id,opening_stock,reorder_level,safety_stock,max_stock,current_stock,warehouse_bin
0,P001,DEL001,196,59,46,340,115928,C15
1,P001,PUN001,198,70,43,349,109389,D16
2,P001,CHN001,187,62,44,311,99373,A11
3,P001,HYD001,226,71,65,417,108772,A10
4,P001,KOL001,263,94,58,475,103808,F03

In [10]:
print("=== INFO ===")
print(inventory.info())

print("\n=== MISSING VALUES ===")
print(inventory.isnull().sum())

print("\n=== SAMPLE DATA ===")
inventory.head()

=== INFO ===
<class 'pandas.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     180 non-null    str
 1   branch_id      180 non-null    str
 2   opening_stock  180 non-null    int64
 3   reorder_level  180 non-null    int64
 4   safety_stock   180 non-null    int64
 5   max_stock      180 non-null    int64
 6   current_stock  180 non-null    int64
 7   warehouse_bin  180 non-null    str
dtypes: int64(5), str(3)
memory usage: 11.4 KB
None

=== MISSING VALUES ===
product_id       0
branch_id        0
opening_stock    0
reorder_level    0
safety_stock     0
max_stock        0
current_stock    0
warehouse_bin    0
dtype: int64

=== SAMPLE DATA ===

,product_id,branch_id,opening_stock,reorder_level,safety_stock,max_stock,current_stock,warehouse_bin
0,P001,DEL001,196,59,46,340,115928,C15
1,P001,PUN001,198,70,43,349,109389,D16
2,P001,CHN001,187,62,44,311,99373,A11
3,P001,HYD001,226,71,65,417,108772,A10
4,P001,KOL001,263,94,58,475,103808,F03

In [11]:
inventory['product_id'] = inventory['product_id'].str.upper()
inventory['branch_id'] = inventory['branch_id'].str.upper()
inventory['warehouse_bin'] = inventory['warehouse_bin'].str.upper()

In [12]:
inventory['stock_availability_pct'] = (
    inventory['current_stock'] / inventory['max_stock']
)

In [13]:
inventory['reorder_flag'] = (
    inventory['current_stock'] <= inventory['reorder_level']
).astype(int)

In [14]:
inventory['safety_breach'] = (
    inventory['current_stock'] < inventory['safety_stock']
).astype(int)

In [15]:
numeric_cols = [
    'opening_stock',
    'reorder_level',
    'safety_stock',
    'max_stock',
    'current_stock'
]




inventory.duplicated(subset=['product_id', 'branch_id']).sum()
inventory[numeric_cols].describe()
inventory['warehouse_bin'].unique()

<StringArray>
['C15', 'D16', 'A11', 'A10', 'F03', 'C20', 'A06', 'E01', 'B04', 'A02', 'F18',
 'E04', 'B07', 'F09', 'C09', 'E12', 'D02', 'C06', 'A14', 'E16', 'A15', 'D18',
 'B06', 'C08', 'E03', 'B10', 'E05', 'C13', 'B19', 'B09', 'F02', 'D03', 'F19',
 'B13', 'A01', 'C04', 'E17', 'C16', 'C03', 'D12', 'A08', 'D04', 'D10', 'D11',
 'E10', 'B15', 'D20', 'F12', 'A13', 'B01', 'F06', 'E15', 'B08', 'D13', 'B05',
 'A16', 'F04', 'F17', 'F11', 'E18', 'D08', 'D06', 'F14', 'C17', 'E07', 'B18',
 'A07', 'C19', 'F05', 'E13', 'B03', 'F08', 'D07', 'D17', 'E11', 'A03', 'F01',
 'F16', 'C11', 'C14', 'E20', 'B16', 'B12', 'A17', 'C02', 'D14', 'C07', 'B02',
 'F20', 'F10', 'C01', 'B17', 'E08', 'C10', 'A05']
Length: 95, dtype: str

In [16]:
inventory.to_csv('../data/processed/inventory_master.csv', index=False)