In [2]:
import pandas as pd
so_header= pd.read_csv('../data/raw/sales_orders_header.csv')
print(so_header.head())

       so_id customer_id branch_id  order_date delivery_date order_status  \
0  SO-990591       C0070    AHM001  2022-05-24    2022-05-28    Delivered
1  SO-431510       C0031    KOL001  2022-05-01    2022-05-08    Delivered
2  SO-495859       C0013    AHM001  2023-10-01    2023-10-02    Delivered
3  SO-745068       C0382    HYD001  2021-10-04    2021-10-09    Delivered
4  SO-175713       C0472    CHN001  2024-10-31    2024-11-04    Delivered

  payment_terms  total_order_value  total_gst_amount  grand_total  \
0        Net 30            1345720          374439.6    1720159.6
1       Advance            2194850          609423.0    2804273.0
2       Advance            2620800          733824.0    3354624.0
3       Advance            1094950          292961.0    1387911.0
4        Net 45               1250             225.0       1475.0

    sales_channel
0    Counter Sale
1  Dealer Network
2          Online
3          Online
4    Counter Sale

In [3]:
print("===INFO===")
print(so_header.info())

print("===MISSING VALUES===")
print(so_header.isnull().sum())

print("\n=== SHAPE ===")
print(so_header.shape)

print("===SAMPLE DATA===")
print(so_header.sample(5))

===INFO===
<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   so_id              20000 non-null  str
 1   customer_id        20000 non-null  str
 2   branch_id          20000 non-null  str
 3   order_date         20000 non-null  str
 4   delivery_date      20000 non-null  str
 5   order_status       20000 non-null  str
 6   payment_terms      20000 non-null  str
 7   total_order_value  20000 non-null  int64
 8   total_gst_amount   20000 non-null  float64
 9   grand_total        20000 non-null  float64
 10  sales_channel      20000 non-null  str
dtypes: float64(2), int64(1), str(8)
memory usage: 1.7 MB
None
===MISSING VALUES===
so_id                0
customer_id          0
branch_id            0
order_date           0
delivery_date        0
order_status         0
payment_terms        0
total_order_value    0
total_gst_amount     0
grand_total          0
sales_channel        0
dtype: int64

=== SHAPE ===
(20000, 11)
===SAMPLE DATA===
           so_id customer_id branch_id  order_date delivery_date order_status  \
13146  SO-187814       C0368    CHN001  2021-09-28    2021-10-10    Delivered
8385   SO-912080       C0032    AHM001  2022-01-14    2022-01-24    Delivered
17447  SO-274171       C0113    CHN001  2019-08-17    2019-08-20    Delivered
7088   SO-223600       C0145    PUN001  2021-07-22    2021-07-25    Delivered
2      SO-495859       C0013    AHM001  2023-10-01    2023-10-02    Delivered

      payment_terms  total_order_value  total_gst_amount  grand_total  \
13146       Advance            1344550          375604.0    1720154.0
8385         Net 15            1739650          484247.0    2223897.0
17447       Advance            1574520          439843.6    2014363.6
7088         Net 45             399700          111656.0     511356.0
2           Advance            2620800          733824.0    3354624.0

      sales_channel
13146        Online
8385    Field Sales
17447   Field Sales
7088         Online
2            Online

In [5]:
text_cols = [
    'so_id',
    'customer_id',
    'branch_id',
    'order_status',
    'payment_terms',
    'sales_channel'
]

for col in text_cols:
    so_header[col] = (
        so_header[col]
        .str.upper()
        .str.strip()
    )

so_header.head()

,so_id,customer_id,branch_id,order_date,delivery_date,order_status,payment_terms,total_order_value,total_gst_amount,grand_total,sales_channel
0,SO-990591,C0070,AHM001,2022-05-24,2022-05-28,DELIVERED,NET 30,1345720,374439.6,1720159.6,COUNTER SALE
1,SO-431510,C0031,KOL001,2022-05-01,2022-05-08,DELIVERED,ADVANCE,2194850,609423.0,2804273.0,DEALER NETWORK
2,SO-495859,C0013,AHM001,2023-10-01,2023-10-02,DELIVERED,ADVANCE,2620800,733824.0,3354624.0,ONLINE
3,SO-745068,C0382,HYD001,2021-10-04,2021-10-09,DELIVERED,ADVANCE,1094950,292961.0,1387911.0,ONLINE
4,SO-175713,C0472,CHN001,2024-10-31,2024-11-04,DELIVERED,NET 45,1250,225.0,1475.0,COUNTER SALE

In [6]:
so_header['order_date'] = pd.to_datetime(so_header['order_date'],errors='coerce')

so_header['delivery_date'] = pd.to_datetime(so_header['delivery_date'],errors='coerce')

so_header[['order_date', 'delivery_date']].head()

  order_date delivery_date
0 2022-05-24    2022-05-28
1 2022-05-01    2022-05-08
2 2023-10-01    2023-10-02
3 2021-10-04    2021-10-09
4 2024-10-31    2024-11-04

In [8]:
so_header.drop_duplicates(inplace=True)

print("Rows after duplicate removal:")
print(so_header.shape)

Rows after duplicate removal:
(20000, 14)

In [9]:
print("Duplicate SO IDs:")
print(so_header['so_id'].duplicated().sum())

print("\nOrder Status Values:")
print(so_header['order_status'].unique())

print("\nSales Channel Values:")
print(so_header['sales_channel'].unique())

Duplicate SO IDs:
0

Order Status Values:
<StringArray>
['DELIVERED', 'CANCELLED']
Length: 2, dtype: str

Sales Channel Values:
<StringArray>
['COUNTER SALE', 'DEALER NETWORK', 'ONLINE', 'FIELD SALES']
Length: 4, dtype: str

In [10]:
so_header.to_csv('../data/processed/sales_orders_header.csv',
    index=False
)

print("Processed sales_orders_header.csv saved successfully!")

Processed sales_orders_header.csv saved successfully!